[package]
name = "capnproto-test-rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
capnpc = "0.19.0"

[dependencies]
capnp = { version = "0.19.3", features = ["quickcheck"] }
zerocopy = "0.7.32"
